apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: qy25y65b0-go
  janus-idp.io/tekton: qy25y65b0-go
  backstage.io/kubernetes-id: qy25y65b0-go
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qy25y65b0-go
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
